# OpenAI API Configuration
openai_api_key = "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"

# Application Password
admin_password = "woaini1314"
user_password = "wobuaini"
