# OpenAI API Configuration
openai_api_key = "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"

# Application Password
admin_password = "woaini1314"
user_password = "wobuaini"