# OpenAI API Configuration
openai_api_key = "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"

# Application Password
admin_password = "woaini1314"
user_password = "wobuaini"
